import React, {useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
let token='';
async function api(path:string,data?:any){const response=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{'X-Crashlab-Token':token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error??'Request failed');return result;}
function SourceTools(){const [build,setBuild]=useState(''),[file,setFile]=useState(''),[good,setGood]=useState(''),[result,setResult]=useState<any>(null);const read=async(diff=false)=>{try{setResult(await api(diff?'diff?'+new URLSearchParams({good,bad:build}):'source?'+new URLSearchParams({build,file,start:'1',end:'150'})));}catch(e){setResult({error:String(e)});}};return <section><h2>Read historical source</h2><label>Failing / mapped build<input value={build} onChange={e=>setBuild(e.target.value)}/></label><label>Repository-relative source file<input value={file} onChange={e=>setFile(e.target.value)} placeholder="Source/Game/Renderer.cpp"/></label><button onClick={()=>void read()}>Read lines 1–150 at mapped commit</button><label>Last-known-good mapped build<input value={good} onChange={e=>setGood(e.target.value)}/></label><button onClick={()=>void read(true)}>Compare historical builds</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</section>;}
function ExposureTools({summary,enqueue}:any){const [path,setPath]=useState('');return <section><h2>Successful-session exposure</h2><p>Optional CSV uses exact build, GPU and raw driver cohorts with UTC periods. Imported denominators never turn a crash-report share into an individual crash probability.</p><label>Local exposure CSV<input value={path} onChange={e=>setPath(e.target.value)}/></label><button disabled={!path} onClick={()=>enqueue('exposure',{path})}>Import exposure CSV</button>{summary?.exposure.cohorts.length>0&&<pre>{JSON.stringify(summary.exposure,null,2)}</pre>}</section>;}
function App(){
  const filters=useRef<Record<string,string>>({});const [filterValues,setFilterValues]=useState({build:'',gpu:'',driver:''});
  const [tab,setTab]=useState('Overview'),[summary,setSummary]=useState<any>(null),[capabilities,setCapabilities]=useState<any>(null),[jobs,setJobs]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[error,setError]=useState(''),[caseData,setCase]=useState<any>(null),[packet,setPacket]=useState<any>(null),[selected,setSelected]=useState(''),[lang,setLang]=useState('en'),[warsaw,setWarsaw]=useState(false),[path,setPath]=useState(''),[database,setDatabase]=useState('import'),[application,setApplication]=useState(''),[build,setBuild]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[attachments,setAttachments]=useState('all'),[preview,setPreview]=useState<any>(null),[mapping,setMapping]=useState({build:'',repository:'',commit:'',engineVersion:'',lastKnownGood:''});
  const run=async(fn:()=>Promise<any>)=>{try{setError('');await fn();}catch(e){setError(String(e instanceof Error?e.message:e));}};
  const refresh=async()=>{const [s,c,j,r]=await Promise.all([api('summary?'+new URLSearchParams(filters.current)),api('doctor'),api('jobs'),api('reports')]);setSummary(s);setCapabilities(c);setJobs(j);setReports(r);};
  useEffect(()=>{void run(async()=>{const session=await fetch('/api/session').then(r=>r.json());token=session.token;await refresh();});const timer=setInterval(()=>{if(token)void run(refresh);},4000);return()=>clearInterval(timer);},[]);
  const enqueue=(kind:string,payload:any={})=>run(async()=>{await api('jobs',{kind,payload});await refresh();});
  const syncOptions={database,application,build,from:from||undefined,to:to||undefined,attachments};
  const investigate=(cluster:string)=>run(async()=>{setSelected(cluster);setPacket(await api('packet?cluster='+cluster));setTab('Investigate');});
  const download=()=>run(async()=>{const res=await fetch('/api/export?'+new URLSearchParams({cluster:selected,language:lang}),{headers:{'X-Crashlab-Token':token}});if(!res.ok)throw new Error('Export failed');const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download='crashlab-investigation.zip';a.click();URL.revokeObjectURL(url);});
  return <div className="layout"><aside><div className="brand">❄ Permafrost<span>CRASH LAB · LOCAL</span></div>{['Overview','Import & sync','Cases','Investigate','Build mapping'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}<div className="local">Evidence stays on this computer.<br/>AI is optional.</div></aside><main><header><div><span className="eyebrow">UNREAL ENGINE INVESTIGATION</span><h1>{tab}</h1></div><label><input type="checkbox" checked={warsaw} onChange={e=>setWarsaw(e.target.checked)}/> Warsaw time</label></header>{error&&<div role="alert" className="error">{error}</div>}{!!summary?.syntheticReports&&<section><b>Synthetic demo data</b><p>{summary.syntheticReports} invented regression reports are included in this view. These are not live Permafrost findings.</p></section>}{tab==='Overview'&&<section><h2>Filter failure cohorts</h2><div className="formgrid">{Object.entries(filterValues).map(([key,value])=><label key={key}>{key}<input value={value} onChange={e=>setFilterValues({...filterValues,[key]:e.target.value})}/></label>)}</div><button onClick={()=>run(async()=>{filters.current=filterValues;await refresh();})}>Apply filters</button><button onClick={()=>run(async()=>{filters.current={};setFilterValues({build:'',gpu:'',driver:''});await refresh();})}>Clear</button></section>}
    {tab==='Overview'&&<><div className="stats">{[['Reports',summary?.total??0],['Reported machine IDs',summary?.affectedMachineIds??0],['Unknown machine',summary?.unknownMachineReports??0],['Failure signatures',summary?.clusters.length??0]].map(([label,value])=><section key={label}><strong>{value}</strong><span>{label}</span></section>)}</div><section><h2>Capabilities</h2><div className="capabilities">{capabilities&&Object.entries(capabilities).map(([name,c]:any)=><div key={name}><b>{name}</b><p>{c.state}</p>{c.liveGate&&<small>{c.liveGate}</small>}{c.realDecodeGate&&<small>{c.realDecodeGate}</small>}</div>)}</div></section><section><h2>Crash families</h2>{!summary?.total?<p>Import a JSON export or attachment folder to begin. Demo fixtures are explicitly synthetic.</p>:<table><thead><tr><th>Signature</th><th>Family</th><th>Reports</th><th>Machine IDs</th><th>Evidence</th></tr></thead><tbody>{summary.clusters.map((c:any)=><tr key={c.id} onClick={()=>investigate(c.id)}><td><button>{c.id}</button></td><td>{c.family}</td><td>{c.count}</td><td>{c.machines}</td><td>{c.specific?'Specific stack/fault':'Broad; insufficient to infer one cause'}</td></tr>)}</tbody></table>}</section><section><h2>Failure distributions</h2><p>These are shares of reported crashes. No exposure denominator is available.</p><div className="distributions">{summary&&Object.entries(summary.distributions).map(([field,values]:any)=><div key={field}><h3>{field}</h3>{Object.entries(values).map(([label,n]:any)=><div className="barrow" key={label}><span>{label}</span><meter min="0" max={summary.total||1} value={n}/><b>{n}</b></div>)}</div>)}</div></section><section><h2>Coverage and uptime</h2><pre>{JSON.stringify({coverage:summary?.coverage,uptime:summary?.uptime},null,2)}</pre><p>Engine uptime and first-sound stopwatch timing have no assumed alignment. Median is not a peak.</p></section></>}
    {tab==='Import & sync'&&<><section><h2>Import local evidence</h2><p>Select a folder, JSON export or ZIP using its local absolute path. Files are preserved in the local data directory.</p><label>Path<input value={path} onChange={e=>setPath(e.target.value)} placeholder="C:\\CrashExports\\playtest"/></label><label>Database namespace<input value={database} onChange={e=>setDatabase(e.target.value)}/></label><button className="primary" disabled={!path} onClick={()=>enqueue('import',{path,database})}>Import</button><button onClick={()=>enqueue('decode')}>Decode pending GPU dumps</button></section><section><h2>Read-only BugSplat synchronization</h2><p>Configure credentials in .env, then restart. Password authentication may not work for SSO accounts. No credential is sent to the browser.</p><div className="formgrid">{[['Application',application,setApplication],['Build',build,setBuild],['From (UTC ISO)',from,setFrom],['To (UTC ISO)',to,setTo]].map(([name,value,set]:any)=><label key={name}>{name}<input value={value} onChange={e=>set(e.target.value)}/></label>)}<label>Attachment policy<select value={attachments} onChange={e=>setAttachments(e.target.value)}>{['metadata','xml-logs','representative','all'].map(v=><option key={v}>{v}</option>)}</select></label></div><p>Attachments arrive in a vendor ZIP. Selective policies still download the archive to discover its contents.</p><button onClick={()=>run(async()=>setPreview(await api('preview-sync',syncOptions)))}>Preview first page</button><button className="primary" disabled={!preview} onClick={()=>enqueue('sync',syncOptions)}>Start sync</button>{preview&&<pre>{JSON.stringify(preview,null,2)}</pre>}</section></>}
    {tab==='Cases'&&<><section><h2>Incident records</h2><table><thead><tr><th>Case</th><th>Build</th><th>GPU</th><th>Driver</th><th>Time (UTC)</th></tr></thead><tbody>{reports.map(r=><tr key={r.key} onClick={()=>run(async()=>setCase(await api('case?id='+encodeURIComponent(r.key))))}><td><button>{r.key}</button></td><td>{r.fields.build??'Unknown'}</td><td>{r.fields.gpu??'Unknown'}</td><td>{r.fields.driver??'Unknown'}</td><td>{r.fields.timeUtc??'Unknown timezone'}{warsaw&&r.fields.timeUtc&&<small>{new Date(r.fields.timeUtc).toLocaleString('en-GB',{timeZone:'Europe/Warsaw'})} Warsaw</small>}</td></tr>)}</tbody></table></section>{caseData&&<section><h2>{caseData.report?.key}</h2><p>All field candidates remain visible. Conflicts are not silently reconciled.</p><pre>{JSON.stringify(caseData,null,2)}</pre></section>}</>}
    {tab==='Investigate'&&<><section><h2>Evidence packet</h2><p>Select a family from Overview. Review the minimized payload before enabling an external AI request. Export opens in Codex without an API key.</p><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English report</option><option value="pl">Polski raport</option></select><button disabled={!packet} className="primary" onClick={download}>Export ZIP packet</button><button disabled={!packet||capabilities?.ai.state!=='configured'} onClick={()=>enqueue('ai',{cluster:selected,packetId:packet.id})}>Send reviewed packet to configured AI</button>{packet&&<><p>{packet.payloadPolicy}</p><pre>{JSON.stringify(packet,null,2)}</pre></>}</section></>}
    {tab==='Build mapping'&&<section><h2>Historical source mapping</h2><p>Read-only Git snapshots use the exact supplied commit. Current HEAD is never substituted. Source verification does not establish symbol compatibility.</p>{Object.entries(mapping).map(([name,value])=><label key={name}>{name}<input value={value} onChange={e=>setMapping({...mapping,[name]:e.target.value})}/></label>)}<button className="primary" onClick={()=>run(async()=>{await api('mappings',mapping);setError('Mapping saved; symbol identity remains unverified.');})}>Verify and save mapping</button></section>}
    {tab==='Build mapping'&&<SourceTools/>}{tab==='Import & sync'&&<ExposureTools summary={summary} enqueue={enqueue}/>}{tab==='Overview'&&summary?.withinMachine.length>0&&<section><h2>Within-machine observations</h2><p>Machine pseudonyms track reported identifiers. Build/driver associations are confounded and do not prove causality.</p><pre>{JSON.stringify(summary.withinMachine,null,2)}</pre></section>}
    <section><h2>Durable jobs</h2>{!jobs.length?<p>No jobs yet.</p>:jobs.map(j=><div className="job" key={j.id}><div><b>{j.kind}</b> <span>{j.state}</span><small>{j.id}</small>{j.error&&<p>{j.error}</p>}<details><summary>Result / checkpoint</summary><pre>{JSON.stringify(j.checkpoint,null,2)}</pre></details></div>{['queued','running'].includes(j.state)?<button onClick={()=>run(async()=>{await api('cancel',{id:j.id});await refresh();})}>Cancel</button>:['failed','cancelled'].includes(j.state)?<button onClick={()=>run(async()=>{await api('resume',{id:j.id});await refresh();})}>Resume</button>:null}</div>)}</section><footer>Permafrost Crash Lab · Evidence hashes and versioned parsers · Localhost</footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
